[[headers]]
  for = "/*"
  [headers.values]
    Timing-Allow-Origin: "*"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      default-src 'self';
      img-src *;
      frame-src 'self'; 
      child-src 'self'; 
      media-src *;
      script-src 'self';
      style-src 'self';
      frame-ancestors 'self';'''
