[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      default-src 'self';
      img-src *;
      frame-src 'self' *.youtube.com *.vimeo.com *.netlify.com; 
      child-src 'self' *.youtube.com *.vimeo.com *.netlify.com; 
      media-src *;
      script-src 'self';
      style-src 'self';'''
    Timing-Allow-Origin: "*"