name: Checkout and Build

on:
  push:
    branches: [
      main
    ]
  pull_request:
    branches: [
      main
    ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with: 
        node-version: 16.x 

    - uses: actions/checkout@v3

    - name: Build
      run: npm run prepub

    # - name: Commit files
    #   id: commit
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "github-actions"
    #     git add --all
    #     if [-z "$(git status --porcelain)"]; then
    #        echo "::set-output name=push::false"
    #     else
    #        git commit -m "Add changes" -a
    #        echo "::set-output name=push::true"
    #     fi
    #   shell: bash
    
    # - name: Push changes
    #   if: steps.commit.outputs.push == 'true'
    #   uses: ad-m/github-push-action@master
    #   with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Adding Known Hosts
      run: |
        mkdir ~/.ssh/
        ssh-keyscan -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Deploy with rsync
      run: rsync -avz build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
